🔧 Devops: Switch to `ruff` for linting/formatting
aiidateam/qe-tools pull request #78
Opened 2024-07-29 11:11 UTC by mbercx

2024-07-30 09:45 UTC, t-reents submitted a review, later dismissed
LGTM!

2024-08-05 08:59 UTC, sphuber requested changes

2024-08-05 08:59 UTC, sphuber commented on .pre-commit-config.yaml
> +-   repo: https://github.com/astral-sh/ruff-pre-commit
`ruff` does import ordering as well, so you can remove isort as well now

2024-08-05 08:59 UTC, sphuber commented on pyproject.toml
>      'pylint~=2.16.0',
Remove `pylint` requirement

2024-10-17 14:56 UTC, mbercx commented
@sphuber do you still want to have a look at this one? Or do I go ahead?

2024-10-17 18:30 UTC, sphuber commented
> @sphuber do you still want to have a look at this one? Or do I go ahead?

All good, please go ahead. No need to check with me

2024-10-18 05:27 UTC, merged